"""add_timezone_to_settings

Revision ID: 1d71f366e856
Revises: a3f9c2d1e845
Create Date: 2026-03-14 16:20:49.346280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d71f366e856'
down_revision: Union[str, Sequence[str], None] = 'a3f9c2d1e845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('timezone', sa.String(), nullable=True))
    op.drop_index(op.f('uix_settings_twilio_number'), table_name='settings', postgresql_where="((twilio_number)::text <> ''::text)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uix_settings_twilio_number'), 'settings', ['twilio_number'], unique=True, postgresql_where="((twilio_number)::text <> ''::text)")
    op.drop_column('settings', 'timezone')
    # ### end Alembic commands ###
